FROM eclipse-temurin:21-jre

# Working dir
WORKDIR /app

# Copy FILE
COPY target/BlackJack-1.0-SNAPSHOT.jar app.jar

# Entrypoint
ENTRYPOINT ["java", "-jar", "app.jar"]

# Default command
CMD ["server"]
