# Stage 1: Build Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=build /app/target/*-shaded.jar app.jar

# Démarre le serveur automatiquement
ENTRYPOINT ["java", "-jar", "app.jar", "server", "-p", "1234"]
