# Stage 1: Build with Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Stage 2: Image finale
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/classes ./classes
CMD ["java", "-cp", "./classes", "ch.BJCLI.client.Client"]
